### PR TITLE
Fix for bower install

### PR DESCRIPTION
**Pull request by uxxman**
Fix for bower install

### CODE REVIEW

**Comment by nehakadam** [comment]
Are facing any issue while installing DateTimePicker using bower? Because I just tried, I could install component.

[bower.json Specification](https://github.com/bower/spec/blob/master/json.md) does not mention that filenames should be in lowercase, so I kept it same as original filenames.

Please mention the reason for change of filename.

**Comment by uxxman** [comment]
In your bower.json file, the path to your js and css files is 
- "main": ["dist/datetimepicker.js", "dist/datetimepicker.css"]

where as the real file names are "DateTimePicker.js" and "DateTimePicker.css". So, in asset pipelining, the files are missing because its looking for "dist/datetimepicker.js" and "dist/datetimepicker.css" but the correct path is "dist/DateTimePicker.css" and "dist/DateTimePicker.css"

**Comment by nehakadam** [comment]
Yes. I viewd it later. Thanks for a fix.

**Comment by uxxman** [comment]
you're welcome :)

**Pull request merged**
